export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_RESET = 'PASSWORD_RESET_RESET';

export const PASSWORD_RESET_UPDATE_REQUEST = 'PASSWORD_RESET_UPDATE_REQUEST';
export const PASSWORD_RESET_UPDATE_SUCCESS = 'PASSWORD_RESET_UPDATE_SUCCESS';
export const PASSWORD_RESET_UPDATE_FAIL = 'PASSWORD_RESET_UPDATE_FAIL';
export const PASSWORD_RESET_UPDATE_RESET = 'PASSWORD_RESET_UPDATE_RESET';
