export const TODO_CREATE = 'TODO_CREATE';
export const TODO_DELETE = 'TODO_DELETE';
export const TODO_FAIL = 'TODO_FAIL';
export const TODO_FETCH = 'TODO_FETCH';
export const TODO_RESET = 'TODO_RESET';

export const FETCH_SINGLE_TODO = 'FETCH_SINGLE_TODO';

export const CREATE_SUB_TODO_REQUEST = 'CREATE_SUB_TODO_REQUEST';
export const CREATE_SUB_TODO_SUCCESS = 'CREATE_SUB_TODO_SUCCESS';
export const CREATE_SUB_TODO_FAIL = 'CREATE_SUB_TODO_FAIL';

export const DELETE_SUBTASK_REQUEST = 'DELETE_SUBTASK_REQUEST';
export const DELETE_SUBTASK_SUCCESS = 'DELETE_SUBTASK_SUCCESS';
export const DELETE_SUBTASK_FAIL = 'DELETE_SUBTASK_FAIL';

export const ADD_TASK_COMPLETE_REQUEST = 'ADD_TASK_COMPLETE_REQUEST';
export const ADD_TASK_COMPLETE_SUCCESS = 'ADD_TASK_COMPLETE_SUCCESS';
export const ADD_TASK_COMPLETE_FAIL = 'ADD_TASK_COMPLETE_FAIL';