export const PASSWORD_UPDATE_REQUEST  = 'PASSWORD_UPDATE_REQUEST';
export const PASSWORD_UPDATE_SUCCESS  = 'PASSWORD_UPDATE_SUCCESS';
export const PASSWORD_UPDATE_FAIL  = 'PASSWORD_UPDATE_FAIL';
export const PASSWORD_UPDATE_RESET  = 'PASSWORD_UPDATE_RESET';

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL';
export const USER_PROFILE_UPDATE_RESET = 'USER_PROFILE_UPDATE_RESET';

