export const PASSWORD_UPDATE_REQUEST  = 'PASSWORD_UPDATE_REQUEST';
export const PASSWORD_UPDATE_SUCCESS  = 'PASSWORD_UPDATE_SUCCESS';
export const PASSWORD_UPDATE_FAIL  = 'PASSWORD_UPDATE_FAIL';
export const PASSWORD_UPDATE_RESET  = 'PASSWORD_UPDATE_RESET';